# Generated by Django 5.0.6 on 2024-06-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(default="g"),
            preserve_default=False,
        ),
    ]
