# Generated by Django 5.0.6 on 2024-06-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_alter_category_options_restaurant_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
