# Generated by Django 5.0.6 on 2024-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_alter_category_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="hours_of_operation",
            field=models.TextField(blank=True),
        ),
    ]
