# Generated by Django 5.0.6 on 2024-10-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_alter_restaurant_hours_of_operation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="item",
            name="price_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="price_3_descr",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
